## Imports

In [28]:
import sys
import os
import torch
import torch.utils.data as data
import torch.nn as nn

sys.path.append(os.path.abspath('../../'))

import neuro_fuzzy_toolbox as nft

In [29]:
import numpy as np

In [30]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    accuracy_score,
    classification_report,
    multilabel_confusion_matrix
)

In [31]:
from ucimlrepo import fetch_ucirepo

# Parkinsons

## Data

In [32]:
parkinsons = fetch_ucirepo(id=174)

X = parkinsons.data.features
y = parkinsons.data.targets

In [33]:
parkinsons.variables

,name,role,type,demographic,description,units,missing_values
0,name,ID,Categorical,None,None,None,no
1,MDVP:Fo,Feature,Continuous,None,None,Hz,no
2,MDVP:Fhi,Feature,Continuous,None,None,Hz,no
3,MDVP:Flo,Feature,Continuous,None,None,Hz,no
4,MDVP:Jitter,Feature,Continuous,None,None,%,no
5,MDVP:Jitter,Feature,Continuous,None,None,Abs,no
6,MDVP:RAP,Feature,Continuous,None,None,None,no
7,MDVP:PPQ,Feature,Continuous,None,None,None,no
8,Jitter:DDP,Feature,Continuous,None,None,None,no
9,MDVP:Shimmer,Feature,Continuous,None,None,None,no
10,MDVP:Shimmer,Feature,Continuous,None,None,dB,no
11,Shimmer:APQ3,Feature,Continuous,None,None,None,no
12,Shimmer:APQ5,Feature,Continuous,None,None,None,no
13,MDVP:APQ,Feature,Continuous,None,None,None,no
14,Shimmer:DDA,Feature,Continuous,None,None,None,no
15,NHR,Feature,Continuous,None,None,None,no
16,HNR,Feature,Continuous,None,None,None,no
17,status,Target,Integer,None,None,None,no
18,RPDE,Feature,Continuous,None,None,None,no
19,DFA,Feature,Continuous,None,None,None,no
20,spread1,Feature,Continuous,None,None,None,no
21,spread2,Feature,Continuous,None,None,None,no
22,D2,Feature,Continuous,None,None,None,no
23,PPE,Feature,Continuous,None,None,None,no

In [34]:
X

,MDVP:Fo,MDVP:Fhi,MDVP:Flo,MDVP:Jitter,MDVP:Jitter,MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer,...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
0,119.992,157.302,74.997,0.00784,0.00784,0.00370,0.00554,0.01109,0.04374,0.04374,...,0.02971,0.06545,0.02211,21.033,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,122.400,148.650,113.819,0.00968,0.00968,0.00465,0.00696,0.01394,0.06134,0.06134,...,0.04368,0.09403,0.01929,19.085,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,116.682,131.111,111.555,0.01050,0.01050,0.00544,0.00781,0.01633,0.05233,0.05233,...,0.03590,0.08270,0.01309,20.651,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,116.676,137.871,111.366,0.00997,0.00997,0.00502,0.00698,0.01505,0.05492,0.05492,...,0.03772,0.08771,0.01353,20.644,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,116.014,141.781,110.655,0.01284,0.01284,0.00655,0.00908,0.01966,0.06425,0.06425,...,0.04465,0.10470,0.01767,19.649,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,174.188,230.978,94.261,0.00459,0.00459,0.00263,0.00259,0.00790,0.04087,0.04087,...,0.02745,0.07008,0.02764,19.517,0.448439,0.657899,-6.538586,0.121952,2.657476,0.133050
191,209.516,253.017,89.488,0.00564,0.00564,0.00331,0.00292,0.00994,0.02751,0.02751,...,0.01879,0.04812,0.01810,19.147,0.431674,0.683244,-6.195325,0.129303,2.784312,0.168895
192,174.688,240.005,74.287,0.01360,0.01360,0.00624,0.00564,0.01873,0.02308,0.02308,...,0.01667,0.03804,0.10715,17.883,0.407567,0.655683,-6.787197,0.158453,2.679772,0.131728
193,198.764,396.961,74.904,0.00740,0.00740,0.00370,0.00390,0.01109,0.02296,0.02296,...,0.01588,0.03794,0.07223,19.020,0.451221,0.643956,-6.744577,0.207454,2.138608,0.123306
194,214.289,260.277,77.973,0.00567,0.00567,0.00295,0.00317,0.00885,0.01884,0.01884,...,0.01373,0.03078,0.04398,21.209,0.462803,0.664357,-5.724056,0.190667,2.555477,0.148569

In [35]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, stratify=y_train)

In [36]:
unique_classes, counts = np.unique(y_train.values, return_counts=True)
print("Training Data")
print(unique_classes)
print(counts)

Training Data
[0 1]
[26 82]

In [37]:
unique_classes, counts = np.unique(y_val.values, return_counts=True)
print("Validation Data")
print(unique_classes)
print(counts)

Validation Data
[0 1]
[ 7 21]

In [38]:
unique_classes, counts = np.unique(y_test.values, return_counts=True)
print("Testing Data")
print(unique_classes)
print(counts)

Testing Data
[0 1]
[15 44]

In [39]:
scaler = MinMaxScaler(feature_range=(-1, 1))

x_train = scaler.fit_transform(x_train)

x_val = scaler.transform(x_val)
x_test = scaler.transform(x_test)

In [40]:
x_train = torch.from_numpy(x_train)
x_val = torch.from_numpy(x_val)
x_test = torch.from_numpy(x_test)

y_train = torch.from_numpy(y_train.values).squeeze()
y_val = torch.from_numpy(y_val.values).squeeze()
y_test = torch.from_numpy(y_test.values).squeeze()

## Model & Algorithms

### DataLoaders

In [41]:
train_loader = data.DataLoader(
    data.TensorDataset(x_train, y_train), 
    batch_size = 8, 
    shuffle = True)
x_train = train_loader.dataset.tensors[0]
y_train = train_loader.dataset.tensors[1]

In [42]:
val_loader = data.DataLoader(
    data.TensorDataset(x_val, y_val), 
    batch_size = 8, 
    shuffle = True)
x_val = val_loader.dataset.tensors[0]
y_val = val_loader.dataset.tensors[1]

### ANFIS

In [43]:
model = nft.rule_reduced_ANFIS(
    input_size = x_train.shape[1],
    num_mfs = 1,
    outputs = 2,
    output_type='softmax',
    dtype=torch.float64
)

model.init_premises(x_train)

In [44]:
with torch.no_grad():
    pred = model(x_train)

nn.functional.cross_entropy(pred, y_train)

tensor(0.7668, dtype=torch.float64)

In [45]:
#model.init_consequents(x_train, y_train, driver="gelsd", ridge_lambda=1.0)
"""
with torch.no_grad():
    pred = model(x_train)

nn.functional.cross_entropy(pred, y_train)
"""

'\nwith torch.no_grad():\n    pred = model(x_train)\n\nnn.functional.cross_entropy(pred, y_train)\n'

### Learning Algorithm

In [46]:
#loss_fn = nn.functional.binary_cross_entropy
loss_fn = nn.functional.cross_entropy
epochs = 1000
optimizer = torch.optim.Adam
params = {'lr': 0.001}
#optimizer = torch.optim.AdamW
#params = {'lr': 0.01, 'weight_decay': 0.01}
#optimizer = torch.optim.SGD
#params = {'lr': 0.001, 'momentum': 0.9}

early_stopping = nft.EarlyStopping(
    patience=30, 
    #delta=0.0001
)

In [47]:
trainer = nft.Hybrid_learning_algorithm(
    epochs=epochs,
    loss_function=loss_fn,
    ridge_lambda=1.,
    optimizer=optimizer,
    optimizer_params=params,
    early_stopping=early_stopping
)

In [48]:
"""
trainer(model, train_loader, val_loader, verbose=True)

pred = model.predict(x_test)

acc = accuracy_score(y_test, pred)
prec = precision_score(y_test, pred, zero_division=0)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred, zero_division=0)
conf_matrix = confusion_matrix(y_test, pred)
class_rep = classification_report(y_test, pred)

print("\n ------ Evaluation ------")
print("\n")
print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", recall)
print("f1 score:", f1, "\n")

print("Confusion Matrix:")
print(conf_matrix, "\n")

print("Classification Report:")
print(class_rep)
"""

'\ntrainer(model, train_loader, val_loader, verbose=True)\n\npred = model.predict(x_test)\n\nacc = accuracy_score(y_test, pred)\nprec = precision_score(y_test, pred, zero_division=0)\nrecall = recall_score(y_test, pred)\nf1 = f1_score(y_test, pred, zero_division=0)\nconf_matrix = confusion_matrix(y_test, pred)\nclass_rep = classification_report(y_test, pred)\n\nprint("\n ------ Evaluation ------")\nprint("\n")\nprint("Accuracy:", acc)\nprint("Precision:", prec)\nprint("Recall:", recall)\nprint("f1 score:", f1, "\n")\n\nprint("Confusion Matrix:")\nprint(conf_matrix, "\n")\n\nprint("Classification Report:")\nprint(class_rep)\n'

### SONFIS

In [49]:
Ngrow = 20
dGrow = 0.8
Nsplit = 25
eSplit = 0.45
Nvanish = 5
lVanish = 2

max_iterations = 100

anfis_trainer = trainer

sonfis_early_stopping = nft.EarlyStopping(patience=20, delta=0.01)
last_training_iteration = False

In [50]:
sonfis = nft.SONFIS(
    Ngrow=Ngrow,
    dGrow=dGrow,
    Nsplit=Nsplit,
    eSplit=eSplit,
    Nvanish=Nvanish,
    lVanish=lVanish,
    max_iterations=max_iterations,
    ANFIStrainer=anfis_trainer,
    early_stopping=sonfis_early_stopping,
    last_training_iteration=last_training_iteration
)

## Training

In [51]:
%time sonfis(model, train_loader, val_loader, verbose=True)

ITERATION:   0/100

STARTING STATE:
   premises                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      output 1 consequents                                                                                                                                                                                                                             output 2 consequents
         x0                       x1                       x2                       x3                       x4                       x5                      x6                     x7                      x8                       x9                      x10                      x11                      x12                      x13                     x14                      x15                      x16                      x17                      x18                      x19                    x20                      x21                                  x0        x1        x2        x3        x4        x5        x6        x7        x8        x9       x10       x11       x12       x13       x14       x15       x16       x17       x18       x19       x20       x21                             x0        x1        x2        x3        x4        x5        x6        x7        x8        x9      x10       x11       x12       x13       x14       x15       x16       x17       x18       x19       x20       x21
          a    b         c         a    b         c         a    b         c         a    b         c         a    b         c         a    b         c        a    b       c         a    b        c         a    b         c         a    b         c         a    b         c         a    b         c         a    b         c         a    b         c        a    b         c         a    b         c         a    b         c         a    b         c         a    b         c         a    b        c        a    b         c         a    b         c                   c0        c1        c2        c3        c4        c5        c6        c7        c8        c9       c10       c11       c12       c13       c14       c15       c16       c17       c18       c19       c20       c21       c22                   c0        c1        c2        c3        c4        c5        c6        c7        c8        c9      c10       c11       c12       c13       c14       c15       c16       c17       c18       c19       c20       c21       c22
0  0.486197  4.0 -0.215111  0.299114  4.0 -0.647625  0.518772  4.0 -0.401041  0.306998  4.0 -0.715363  0.306998  4.0 -0.715363  0.289954  4.0 -0.748002  0.34046  4.0 -0.6746  0.289926  4.0 -0.74801  0.426693  4.0 -0.522756  0.426693  4.0 -0.522756  0.395324  4.0 -0.557031  0.509506  4.0 -0.449738  0.475412  4.0 -0.459651  0.395277  4.0 -0.556956  0.27903  4.0 -0.842523  0.394583  4.0  0.075438  0.498557  4.0  0.123806  0.440531  4.0  0.144601  0.441957  4.0 -0.102581  0.405438  4.0 -0.00021  0.37198  4.0 -0.162796  0.454255  4.0 -0.195068             0.195119 -0.008863  0.094707  0.150887  0.150887 -0.203377  0.119545 -0.202807 -0.035355 -0.035355 -0.025286  0.118307 -0.142661 -0.025116  0.243727  0.061215  0.022921 -0.046658 -0.236385  0.018965 -0.214656 -0.081858  0.356423            -0.178568 -0.044543 -0.113359 -0.150826 -0.150826  0.174193 -0.088733  0.173585  0.039425  0.039425  0.00745 -0.103304  0.126169  0.007261 -0.322854 -0.126189 -0.031077  0.027931  0.241311 -0.016106  0.204421  0.086856  0.499637

	loss: 0.766821 - validation loss: 0.910977
	 --> ANFIS rules: 1


ITERATION:   1/100
	-> Growing 1 new subnets: [1]

CURRENT STATE:
   premises                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         output 1 consequents                                                                                                                                                                                                                             output 2 consequents
         x0                            x1                            x2                            x3                            x4                            x5                            x6                            x7                            x8                            x9                           x10                           x11                           x12                           x13                           x14                           x15                          x16                           x17                           x18                          x19                           x20                           x21                                       x0        x1        x2        x3        x4        x5        x6        x7        x8        x9       x10       x11       x12       x13       x14       x15       x16       x17       x18       x19       x20       x21                             x0        x1        x2        x3        x4        x5        x6        x7        x8        x9      x10       x11       x12       x13       x14       x15       x16       x17       x18       x19       x20       x21
          a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a        b         c         a         b         c         a         b         c         a        b         c         a         b         c         a         b         c         a         b         c                   c0        c1        c2        c3        c4        c5        c6        c7        c8        c9       c10       c11       c12       c13       c14       c15       c16       c17       c18       c19       c20       c21       c22                   c0        c1        c2        c3        c4        c5        c6        c7        c8        c9      c10       c11       c12       c13       c14       c15       c16       c17       c18       c19       c20       c21       c22
0  0.486197       4.0 -0.215111  0.299114       4.0 -0.647625  0.518772       4.0 -0.401041  0.306998       4.0 -0.715363  0.306998       4.0 -0.715363  0.289954       4.0 -0.748002   0.34046       4.0   -0.6746  0.289926       4.0  -0.74801  0.426693       4.0 -0.522756  0.426693       4.0 -0.522756  0.395324       4.0 -0.557031  0.509506       4.0 -0.449738  0.475412       4.0 -0.459651  0.395277       4.0 -0.556956   0.27903       4.0 -0.842523  0.394583      4.0  0.075438  0.498557       4.0  0.123806  0.440531       4.0  0.144601  0.441957      4.0 -0.102581  0.405438       4.0  -0.00021   0.37198       4.0 -0.162796  0.454255       4.0 -0.195068             0.195119 -0.008863  0.094707  0.150887  0.150887 -0.203377  0.119545 -0.202807 -0.035355 -0.035355 -0.025286  0.118307 -0.142661 -0.025116  0.243727  0.061215  0.022921 -0.046658 -0.236385  0.018965 -0.214656 -0.081858  0.356423            -0.178568 -0.044543 -0.113359 -0.150826 -0.150826  0.174193 -0.088733  0.173585  0.039425  0.039425  0.00745 -0.103304  0.126169  0.007261 -0.322854 -0.126189 -0.031077  0.027931  0.241311 -0.016106  0.204421  0.086856  0.499637
1   0.71664  3.823084 -0.134319  0.400104  4.070472 -0.639437  0.537963  3.898129 -0.208571  0.401821  4.046621 -0.722356  0.401821  4.046621 -0.722356  0.330326  3.939553 -0.699502  0.410653  3.966268 -0.639278  0.330932  3.941016 -0.700234  0.471443  3.816922 -0.440992  0.471443  3.816922 -0.440992  0.375068  3.868277 -0.426248  0.516947  3.866084 -0.312007  0.559599  3.893925 -0.488007  0.374929  3.868232 -0.426097  0.383803  3.997904 -0.775131  0.455102  3.87281  0.139089   0.35554  4.195473  0.142192  0.541307  3.994971  0.206309  0.567456  3.88971 -0.161083  0.391516  4.070328 -0.037033  0.356595  4.005142 -0.202152  0.621294  3.894603 -0.233986             0.300936  0.000188 -0.021955  0.056824  0.056824 -0.098114  0.182926 -0.098131 -0.065095 -0.065095 -0.145525  0.271233 -0.104725 -0.145316  0.154299  0.096745  0.111254 -0.142271 -0.265186 -0.178377 -0.174127 -0.046254  0.347042            -0.280791 -0.052993 -0.012028 -0.058066 -0.058066  0.078020 -0.155405  0.077931  0.064839  0.064839  0.11884 -0.257706  0.092207  0.118627 -0.258495 -0.204247 -0.105608  0.124340  0.283188  0.156434  0.148578  0.042642  0.489618

	loss: 0.451156 - validation loss: 0.473835
	 --> ANFIS rules: 2


ITERATION:   2/100
	-> Growing 2 new subnets: [2, 3]

CURRENT STATE:
   premises                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           output 1 consequents                                                                                                                                                                                                                             output 2 consequents
         x0                            x1                            x2                            x3                            x4                            x5                            x6                            x7                            x8                            x9                           x10                           x11                           x12                           x13                           x14                           x15                           x16                           x17                           x18                           x19                           x20                           x21                                       x0        x1        x2        x3        x4        x5        x6        x7        x8        x9       x10       x11       x12       x13       x14       x15       x16       x17       x18       x19       x20       x21                             x0        x1        x2        x3        x4        x5        x6        x7        x8        x9       x10       x11       x12       x13       x14       x15       x16       x17       x18       x19       x20       x21
          a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c                   c0        c1        c2        c3        c4        c5        c6        c7        c8        c9       c10       c11       c12       c13       c14       c15       c16       c17       c18       c19       c20       c21       c22                   c0        c1        c2        c3        c4        c5        c6        c7        c8        c9       c10       c11       c12       c13       c14       c15       c16       c17       c18       c19       c20       c21       c22
0  0.486197       4.0 -0.215111  0.299114       4.0 -0.647625  0.518772       4.0 -0.401041  0.306998       4.0 -0.715363  0.306998       4.0 -0.715363  0.289954       4.0 -0.748002   0.34046       4.0   -0.6746  0.289926       4.0  -0.74801  0.426693       4.0 -0.522756  0.426693       4.0 -0.522756  0.395324       4.0 -0.557031  0.509506       4.0 -0.449738  0.475412       4.0 -0.459651  0.395277       4.0 -0.556956   0.27903       4.0 -0.842523  0.394583       4.0  0.075438  0.498557       4.0  0.123806  0.440531       4.0  0.144601  0.441957       4.0 -0.102581  0.405438       4.0  -0.00021   0.37198       4.0 -0.162796  0.454255       4.0 -0.195068             0.195119 -0.008863  0.094707  0.150887  0.150887 -0.203377  0.119545 -0.202807 -0.035355 -0.035355 -0.025286  0.118307 -0.142661 -0.025116  0.243727  0.061215  0.022921 -0.046658 -0.236385  0.018965 -0.214656 -0.081858  0.356423            -0.178568 -0.044543 -0.113359 -0.150826 -0.150826  0.174193 -0.088733  0.173585  0.039425  0.039425  0.007450 -0.103304  0.126169  0.007261 -0.322854 -0.126189 -0.031077  0.027931  0.241311 -0.016106  0.204421  0.086856  0.499637
1   0.71664  3.823084 -0.134319  0.400104  4.070472 -0.639437  0.537963  3.898129 -0.208571  0.401821  4.046621 -0.722356  0.401821  4.046621 -0.722356  0.330326  3.939553 -0.699502  0.410653  3.966268 -0.639278  0.330932  3.941016 -0.700234  0.471443  3.816922 -0.440992  0.471443  3.816922 -0.440992  0.375068  3.868277 -0.426248  0.516947  3.866084 -0.312007  0.559599  3.893925 -0.488007  0.374929  3.868232 -0.426097  0.383803  3.997904 -0.775131  0.455102   3.87281  0.139089   0.35554  4.195473  0.142192  0.541307  3.994971  0.206309  0.567456   3.88971 -0.161083  0.391516  4.070328 -0.037033  0.356595  4.005142 -0.202152  0.621294  3.894603 -0.233986             0.300936  0.000188 -0.021955  0.056824  0.056824 -0.098114  0.182926 -0.098131 -0.065095 -0.065095 -0.145525  0.271233 -0.104725 -0.145316  0.154299  0.096745  0.111254 -0.142271 -0.265186 -0.178377 -0.174127 -0.046254  0.347042            -0.280791 -0.052993 -0.012028 -0.058066 -0.058066  0.078020 -0.155405  0.077931  0.064839  0.064839  0.118840 -0.257706  0.092207  0.118627 -0.258495 -0.204247 -0.105608  0.124340  0.283188  0.156434  0.148578  0.042642  0.489618
2  0.475867  4.143468 -0.377802  0.315149  4.091768 -0.772971  0.189672  4.260127 -0.480734  0.067221  4.465022 -0.818324  0.067221  4.465022 -0.818324  0.044552  4.117739  -0.92249  0.069556  4.213398 -0.874696  0.043738  4.138996 -0.921949  0.247392  4.036999 -0.757829  0.247392  4.036999 -0.757829  0.206103  3.946562 -0.757641   0.29894  4.092087  -0.77093  0.318164  4.050539 -0.705227   0.20651  3.948183 -0.757869  0.068229  4.009726 -0.956955  0.290966  4.064431  0.302912  0.573334  4.339652 -0.045605  0.375836  4.208763  0.215657  0.494411  4.079545 -0.287981  0.447786  4.132867 -0.073407   0.39183   4.05729 -0.226476  0.421472  4.129042 -0.379162            -0.043749 -0.079442 -0.022715 -0.072130 -0.072130 -0.097044 -0.092114 -0.097072 -0.072787 -0.072787 -0.068317 -0.090458 -0.066249 -0.068294 -0.098072 -0.005798  0.102169  0.001034 -0.074949  0.049522 -0.032619 -0.099373  0.104471            -0.006182  0.009804 -0.013757  0.004479  0.004479  0.023409  0.022545  0.023436  0.008512  0.008512  0.004311  0.024016  0.004729  0.004302  0.019933  0.030663 -0.107976  0.031197  0.044649 -0.057442 -0.006922  0.058102 -0.023627
3  0.699056  4.235096 -0.279107  0.295812  4.087193  -0.75511  0.799022  4.179125 -0.208803  0.317407   4.10358 -0.631413  0.317407   4.10358 -0.631413  0.400606  4.141589 -0.620119  0.428714  4.159462 -0.517113  0.400054  4.142889 -0.620105  0.553067  4.180291 -0.349711  0.553067  4.180291 -0.349711  0.514864  4.172718 -0.397535  0.671833  4.161794 -0.235592  0.613227   4.19657 -0.268443  0.514861  4.172665 -0.397536  0.294881  4.060506 -0.806914  0.432116  4.081266  -0.07975  0.481471  3.963502  0.253999  0.654984  4.083077  0.362968  0.464522  4.265272  0.075334  0.506078  3.985021 -0.012447  0.417276   4.20184  -0.32851  0.506023   4.28761  0.033588            -0.009913 -0.004232 -0.028369  0.000415  0.000415 -0.003902  0.005825 -0.003954  0.005165  0.005165 -0.000403  0.008143  0.016730 -0.000395  0.007515  0.004775  0.025964  0.018456 -0.012681  0.022530  0.010093 -0.001282 -0.049265             0.027625 -0.086535 -0.052913 -0.004082 -0.004082 -0.016267  0.021448 -0.016314 -0.000105 -0.000105 -0.003559 -0.012760 -0.024101 -0.003584 -0.151890 -0.211108 -0.003681 -0.016322  0.074580 -0.059534 -0.044094  0.014610  0.752423

	loss: 0.380422 - validation loss: 0.468417
	 --> ANFIS rules: 4


ITERATION:   3/100
	-> Splitting 1 subnets: [0]

CURRENT STATE:
   premises                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           output 1 consequents                                                                                                                                                                                                                                                                                                                     output 2 consequents
         x0                            x1                            x2                            x3                            x4                            x5                            x6                            x7                            x8                            x9                           x10                           x11                           x12                           x13                           x14                           x15                           x16                           x17                           x18                           x19                           x20                           x21                                       x0            x1            x2            x3            x4            x5            x6            x7            x8            x9           x10           x11           x12           x13           x14           x15           x16           x17           x18           x19           x20           x21                                 x0            x1            x2            x3            x4            x5            x6            x7            x8            x9           x10           x11           x12           x13           x14           x15           x16           x17           x18           x19           x20           x21

## Evaluation

### Test data

In [52]:
pred = model.predict(x_test)

acc = accuracy_score(y_test, pred)
prec = precision_score(y_test, pred, zero_division=0)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred, zero_division=0)
conf_matrix = confusion_matrix(y_test, pred)
#mul_label_conf_matrix = multilabel_confusion_matrix(y_test, pred)
class_rep = classification_report(y_test, pred)

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", recall)
print("f1 score:", f1, "\n")

print("Confusion Matrix:")
print(conf_matrix, "\n")

#print("Multilabel Confusion Matrix:")
#print(mul_label_conf_matrix, "\n")

print("Classification Report:")
print(class_rep)

Accuracy: 0.8813559322033898
Precision: 0.9302325581395349
Recall: 0.9090909090909091
f1 score: 0.9195402298850575

Confusion Matrix:
[[12  3]
 [ 4 40]]

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.80      0.77        15
           1       0.93      0.91      0.92        44

    accuracy                           0.88        59
   macro avg       0.84      0.85      0.85        59
weighted avg       0.88      0.88      0.88        59

### Training data

In [53]:
pred = model.predict(x_train)

acc = accuracy_score(y_train, pred)
prec = precision_score(y_train, pred, zero_division=0)
recall = recall_score(y_train, pred)
f1 = f1_score(y_train, pred, zero_division=0)
conf_matrix = confusion_matrix(y_train, pred)
class_rep = classification_report(y_train, pred)

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", recall)
print("f1 score:", f1, "\n")

print("Confusion Matrix:")
print(conf_matrix, "\n")

print("Classification Report:")
print(class_rep)

Accuracy: 0.9907407407407407
Precision: 1.0
Recall: 0.9878048780487805
f1 score: 0.9938650306748467

Confusion Matrix:
[[26  0]
 [ 1 81]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        26
           1       1.00      0.99      0.99        82

    accuracy                           0.99       108
   macro avg       0.98      0.99      0.99       108
weighted avg       0.99      0.99      0.99       108

In [54]:
print(model.get_rules_structure().to_string())

        premises                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           output 1 consequents                                                                                                                                                                                                                             output 2 consequents
              x0                            x1                            x2                            x3                            x4                            x5                            x6                            x7                            x8                            x9                           x10                           x11                           x12                           x13                           x14                           x15                           x16                           x17                           x18                           x19                           x20                           x21                                       x0        x1        x2        x3        x4        x5        x6        x7        x8        x9       x10       x11       x12       x13       x14       x15       x16       x17       x18       x19       x20       x21                             x0        x1        x2        x3        x4        x5        x6        x7        x8        x9       x10       x11       x12       x13       x14       x15       x16       x17       x18       x19       x20       x21
               a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c         a         b         c                   c0        c1        c2        c3        c4        c5        c6        c7        c8        c9       c10       c11       c12       c13       c14       c15       c16       c17       c18       c19       c20       c21       c22                   c0        c1        c2        c3        c4        c5        c6        c7        c8        c9       c10       c11       c12       c13       c14       c15       c16       c17       c18       c19       c20       c21       c22
rule 1   0.71664  3.823084 -0.134319  0.400104  4.070472 -0.639437  0.537963  3.898129 -0.208571  0.401821  4.046621 -0.722356  0.401821  4.046621 -0.722356  0.330326  3.939553 -0.699502  0.410653  3.966268 -0.639278  0.330932  3.941016 -0.700234  0.471443  3.816922 -0.440992  0.471443  3.816922 -0.440992  0.375068  3.868277 -0.426248  0.516947  3.866084 -0.312007  0.559599  3.893925 -0.488007  0.374929  3.868232 -0.426097  0.383803  3.997904 -0.775131  0.455102   3.87281  0.139089   0.35554  4.195473  0.142192  0.541307  3.994971  0.206309  0.567456   3.88971 -0.161083  0.391516  4.070328 -0.037033  0.356595  4.005142 -0.202152  0.621294  3.894603 -0.233986             0.300936  0.000188 -0.021955  0.056824  0.056824 -0.098114  0.182926 -0.098131 -0.065095 -0.065095 -0.145525  0.271233 -0.104725 -0.145316  0.154299  0.096745  0.111254 -0.142271 -0.265186 -0.178377 -0.174127 -0.046254  0.347042            -0.280791 -0.052993 -0.012028 -0.058066 -0.058066  0.078020 -0.155405  0.077931  0.064839  0.064839  0.118840 -0.257706  0.092207  0.118627 -0.258495 -0.204247 -0.105608  0.124340  0.283188  0.156434  0.148578  0.042642  0.489618
rule 2  0.475867  4.143468 -0.377802  0.315149  4.091768 -0.772971  0.189672  4.260127 -0.480734  0.067221  4.465022 -0.818324  0.067221  4.465022 -0.818324  0.044552  4.117739  -0.92249  0.069556  4.213398 -0.874696  0.043738  4.138996 -0.921949  0.247392  4.036999 -0.757829  0.247392  4.036999 -0.757829  0.206103  3.946562 -0.757641   0.29894  4.092087  -0.77093  0.318164  4.050539 -0.705227   0.20651  3.948183 -0.757869  0.068229  4.009726 -0.956955  0.290966  4.064431  0.302912  0.573334  4.339652 -0.045605  0.375836  4.208763  0.215657  0.494411  4.079545 -0.287981  0.447786  4.132867 -0.073407   0.39183   4.05729 -0.226476  0.421472  4.129042 -0.379162            -0.043749 -0.079442 -0.022715 -0.072130 -0.072130 -0.097044 -0.092114 -0.097072 -0.072787 -0.072787 -0.068317 -0.090458 -0.066249 -0.068294 -0.098072 -0.005798  0.102169  0.001034 -0.074949  0.049522 -0.032619 -0.099373  0.104471            -0.006182  0.009804 -0.013757  0.004479  0.004479  0.023409  0.022545  0.023436  0.008512  0.008512  0.004311  0.024016  0.004729  0.004302  0.019933  0.030663 -0.107976  0.031197  0.044649 -0.057442 -0.006922  0.058102 -0.023627
rule 3  0.699056  4.235096 -0.279107  0.295812  4.087193  -0.75511  0.799022  4.179125 -0.208803  0.317407   4.10358 -0.631413  0.317407   4.10358 -0.631413  0.400606  4.141589 -0.620119  0.428714  4.159462 -0.517113  0.400054  4.142889 -0.620105  0.553067  4.180291 -0.349711  0.553067  4.180291 -0.349711  0.514864  4.172718 -0.397535  0.671833  4.161794 -0.235592  0.613227   4.19657 -0.268443  0.514861  4.172665 -0.397536  0.294881  4.060506 -0.806914  0.432116  4.081266  -0.07975  0.481471  3.963502  0.253999  0.654984  4.083077  0.362968  0.464522  4.265272  0.075334  0.506078  3.985021 -0.012447  0.417276   4.20184  -0.32851  0.506023   4.28761  0.033588            -0.009913 -0.004232 -0.028369  0.000415  0.000415 -0.003902  0.005825 -0.003954  0.005165  0.005165 -0.000403  0.008143  0.016730 -0.000395  0.007515  0.004775  0.025964  0.018456 -0.012681  0.022530  0.010093 -0.001282 -0.049265             0.027625 -0.086535 -0.052913 -0.004082 -0.004082 -0.016267  0.021448 -0.016314 -0.000105 -0.000105 -0.003559 -0.012760 -0.024101 -0.003584 -0.151890 -0.211108 -0.003681 -0.016322  0.074580 -0.059534 -0.044094  0.014610  0.752423
rule 4  0.486154  3.985823  0.247035  0.231562  4.015891 -0.505571  0.741553  3.911532  0.039925  0.138673  4.149739 -0.890533  0.138673  4.149739 -0.890533  0.128646  4.093396 -0.873529  0.113997  4.117979 -0.877062  0.128266  4.093984 -0.873573  0.153312  4.027555 -0.829284  0.153312  4.027555 -0.829284  0.146259   4.00647 -0.834968  0.134336  4.004766 -0.833975  0.172628  3.978604 -0.795125  0.146203  4.006492 -0.834935  0.076947  4.033006 -0.875111  0.384115  4.003203  0.383587  0.426656  3.991466 -0.402754  0.423276   3.98788 -0.118829  0.206025  4.056314 -0.635882   0.19977  4.076006 -0.235054  0.381231  3.924295 -0.301119  0.192876  4.011453 -0.694523             0.436965  0.143895  0.230250 -0.006832 -0.006832  0.010181 -0.003803  0.009769  0.007109  0.007109  0.013686  0.039364 -0.048341  0.013783 -0.025217  0.173049  0.179559 -0.049212 -0.270912 -0.146946 -0.157673 -0.227954  0.021355            -0.396097 -0.196795 -0.217242 -0.071009 -0.071009 -0.087450 -0.070159 -0.087001 -0.069776 -0.069776 -0.074727 -0.095515 -0.016751 -0.074825 -0.071712 -0.211832 -0.204478  0.036536  0.241444  0.105328  0.160421  0.192256  0.082592
rule 5  0.387499  3.981865 -0.259429  0.351243  4.094242 -0.589489  0.410996  3.979256 -0.458846   0.29663  4.039692 -0.366116   0.29663  4.039692 -0.366116   0.36289  3.917274 -0.476248  0.464127  3.888068 -0.391324  0.362665  3.917237 -0.476093  0.530998  4.064707 -0.214723  0.530998  4.064707 -0.214723  0.480403  4.106338 -0.292809  0.682018  3.974125 -0.074519  0.579884    4.0302 -0.107935  0.480322  4.106454 -0.292741  0.409595    3.9504 -0.682907   0.39238  4.018375 -0.232855  0.497716  3.986344  0.252196  0.497945  3.990294  0.206742   0.44419  3.973009  0.304922   0.41164  4.010058  0.349691  0.267857  3.987553  0.110533  0.467789  4.036631  0.236269             0.002933 -0.001031 -0.000400  0.001483  0.001483  0.000247  0.001527  0.000249 -0.001048 -0.001048 -0.000976  0.001911 -0.001390 -0.000977 -0.000555 -0.001811 -0.000232 -0.005440 -0.000677  0.003367  0.001630 -0.000614 -0.001763            -0.091397 -0.033883 -0.135103  0.006132  0.006132 -0.016539  0.023004 -0.016625 -0.007095 -0.007095 -0.020613  0.015887 -0.002141 -0.020608 -0.128269 -0.168170  0.024923  0.027656  0.084516  0.055288  0.084586  0.020722  0.614586