In [1]:
import sys
import os
import torch
import torch.utils.data as data
import torch.nn as nn

sys.path.append(os.path.abspath('../'))

from neuro_fuzzy_toolbox_old import Type3ANFIS

# Gradient testing

## Rule reduced ANFIS

### Regression

#### Single output

In [2]:
x = torch.rand(10, 3)
y = torch.rand(10)
y

tensor([0.4965, 0.8307, 0.8348, 0.5190, 0.5205, 0.9491, 0.5776, 0.8629, 0.3253,
        0.7119])

In [3]:
model = Type3ANFIS(x, init_rules=4, output_type='regression', outputs_amount=1)

In [4]:
model.premises.shape

torch.Size([3, 4, 2])

In [5]:
model.premises_structure

         mu (x0)  sigma (x0)   mu (x1)  sigma (x1)   mu (x2)  sigma (x2)
rule 1  0.058655    0.138237  0.074513    0.146243  0.099717    0.143731
rule 2  0.335128    0.138237  0.366999    0.146243  0.387179    0.143731
rule 3  0.611601    0.138237  0.659485    0.146243  0.674640    0.143731
rule 4  0.888075    0.138237  0.951971    0.146243  0.962101    0.143731

In [6]:
model.consequents.shape

torch.Size([1, 4, 4])

In [7]:
model.consequents_structure

[         c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1  0.143940  0.156809 -0.290823  0.075153
 rule 2  0.290259 -0.169580  0.044711 -0.808492
 rule 3  0.395355  0.161677 -0.230918 -0.714224
 rule 4 -0.564566 -0.100642 -0.895114 -0.137524]

In [8]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [9]:
model(x)

tensor([[-0.6988],
        [-0.5915],
        [-0.4945],
        [-0.8325],
        [-0.4448],
        [-0.6972],
        [-0.6809],
        [-0.7061],
        [-0.6398],
        [-0.5236]], grad_fn=<TBackward0>)

In [10]:
y

tensor([0.9132, 0.7911, 0.7347, 0.2263, 0.3134, 0.6408, 0.0220, 0.5377, 0.3738,
        0.4720])

In [11]:
print(model.fuzzify_layer.premises.grad)

None

In [12]:
print(model.consequent_layer.consequents.grad)

None

In [13]:
model(x)

tensor([[-0.6988],
        [-0.5915],
        [-0.4945],
        [-0.8325],
        [-0.4448],
        [-0.6972],
        [-0.6809],
        [-0.7061],
        [-0.6398],
        [-0.5236]], grad_fn=<TBackward0>)

In [14]:
model(x).squeeze()

tensor([-0.6988, -0.5915, -0.4945, -0.8325, -0.4448, -0.6972, -0.6809, -0.7061,
        -0.6398, -0.5236], grad_fn=<SqueezeBackward0>)

In [15]:
loss = nn.functional.mse_loss(model(x).squeeze(), y)
loss

tensor(1.3567, grad_fn=<MseLossBackward0>)

In [16]:
loss.backward()

In [17]:
print(model.fuzzify_layer.premises.grad)

tensor([[[-0.6161, -0.9781],
         [ 0.0647,  2.3280],
         [-0.0782, -0.5114],
         [-0.3330,  0.9378]],

        [[-0.4263, -0.7963],
         [-0.5048,  1.0949],
         [ 0.0338, -0.8692],
         [-0.0126,  0.0258]],

        [[-0.8101, -1.3249],
         [-0.2822,  0.6302],
         [ 0.3027, -1.6247],
         [-0.1363,  0.1742]]])

In [18]:
print(model.consequent_layer.consequents.grad)

tensor([[[-0.0279, -0.0209, -0.0389, -0.1170],
         [-0.4233, -0.4007, -0.5208, -1.2140],
         [-0.5087, -0.5203, -0.6491, -0.9079],
         [-0.0141, -0.0262, -0.0223, -0.0280]]])

#### Multiple outputs

In [4]:
x = torch.rand(10, 3)
y = torch.rand(10, 2)
y

tensor([[0.3100, 0.8925],
        [0.4932, 0.3075],
        [0.3062, 0.3602],
        [0.9847, 0.7587],
        [0.9073, 0.0297],
        [0.1188, 0.6811],
        [0.4641, 0.3335],
        [0.4059, 0.0053],
        [0.2838, 0.2494],
        [0.5152, 0.4499]])

In [5]:
model = Type3ANFIS(x, init_rules=4, output_type='regression', outputs_amount=2)

In [6]:
model.premises.shape

torch.Size([3, 4, 2])

In [8]:
model.premises_structure

         mu (x0)  sigma (x0)   mu (x1)  sigma (x1)   mu (x2)  sigma (x2)
rule 1  0.015778    0.115846  0.023376    0.159369  0.001748    0.149628
rule 2  0.247470    0.115846  0.342115    0.159369  0.301004    0.149628
rule 3  0.479162    0.115846  0.660853    0.159369  0.600260    0.149628
rule 4  0.710853    0.115846  0.979592    0.159369  0.899516    0.149628

In [9]:
model.consequents.shape

torch.Size([2, 4, 4])

In [10]:
model.consequents_structure

[         c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1 -0.499817 -0.051414 -0.118618  0.028601
 rule 2 -0.849954 -0.533225 -0.183525  0.939140
 rule 3 -0.846595 -0.838631 -0.864406 -0.811930
 rule 4 -0.559824  0.336817 -0.384052  0.816470,
          c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1 -0.186350  0.253000  0.022693  0.530576
 rule 2  0.281543  0.252890 -0.064691  0.135604
 rule 3 -0.902860  0.122554  0.462674 -0.145358
 rule 4 -0.359965 -0.229238  0.070279  0.642220]

In [11]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [12]:
model(x)

tensor([[ 0.4534,  0.3615],
        [ 0.7377,  0.1337],
        [ 0.4863,  0.1525],
        [ 0.1848,  0.4931],
        [ 0.2052,  0.3613],
        [-2.4495,  0.3251],
        [ 0.3997,  0.1427],
        [-2.0738, -0.4059],
        [ 0.5051,  0.2783],
        [-2.3368, -0.2681]], grad_fn=<TBackward0>)

In [13]:
y

tensor([[0.3100, 0.8925],
        [0.4932, 0.3075],
        [0.3062, 0.3602],
        [0.9847, 0.7587],
        [0.9073, 0.0297],
        [0.1188, 0.6811],
        [0.4641, 0.3335],
        [0.4059, 0.0053],
        [0.2838, 0.2494],
        [0.5152, 0.4499]])

In [14]:
print(model.fuzzify_layer.premises.grad)
print(model.consequent_layer.consequents.grad)

None
None

In [15]:
model(x)

tensor([[ 0.4534,  0.3615],
        [ 0.7377,  0.1337],
        [ 0.4863,  0.1525],
        [ 0.1848,  0.4931],
        [ 0.2052,  0.3613],
        [-2.4495,  0.3251],
        [ 0.3997,  0.1427],
        [-2.0738, -0.4059],
        [ 0.5051,  0.2783],
        [-2.3368, -0.2681]], grad_fn=<TBackward0>)

In [16]:
loss = nn.functional.mse_loss(model(x), y)
loss

tensor(1.1781, grad_fn=<MseLossBackward0>)

In [17]:
loss.backward()

In [18]:
print(model.fuzzify_layer.premises.grad)

tensor([[[ 0.0068,  0.0046],
         [-0.2321, -1.4490],
         [ 0.0027,  0.7227],
         [ 0.3620, -1.6478]],

        [[ 0.0822,  0.0946],
         [ 0.0232, -0.1229],
         [-0.0181,  0.7173],
         [ 0.0141, -0.0296]],

        [[ 0.0152, -0.1332],
         [-0.0111, -0.2969],
         [-0.0217,  0.3782],
         [ 0.1256, -0.4106]]])

In [19]:
print(model.consequent_layer.consequents.grad)

tensor([[[-1.4510e-03, -1.5340e-02, -7.2022e-03, -5.7814e-02],
         [-4.9715e-02,  8.9906e-03,  2.6479e-02, -2.3702e-02],
         [-3.1278e-01, -5.8410e-01, -4.9045e-01, -7.8263e-01],
         [-1.0170e-03, -3.3594e-03, -2.3118e-03, -3.5574e-03]],

        [[-5.0585e-04, -5.5867e-03, -3.3233e-03, -2.1122e-02],
         [ 1.4985e-02, -4.3922e-02, -4.4443e-02, -7.8695e-02],
         [-6.2791e-02, -1.1315e-01, -8.7109e-02, -1.4886e-01],
         [-2.3659e-04, -6.5263e-04, -4.0199e-04, -6.9287e-04]]])

### Binary classification

#### Single ouput

In [22]:
x = torch.rand(10, 2)
y = torch.randint(0, 2, (10,))
y

tensor([0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [23]:
model = Type3ANFIS(x, init_rules=4, output_type='binary', outputs_amount=1)
model.premises.shape

torch.Size([2, 4, 2])

In [24]:
model.premises_structure

         mu (x0)  sigma (x0)   mu (x1)  sigma (x1)
rule 1  0.042402    0.158397  0.016281    0.131807
rule 2  0.359197    0.158397  0.279896    0.131807
rule 3  0.675991    0.158397  0.543511    0.131807
rule 4  0.992786    0.158397  0.807125    0.131807

In [25]:
model.consequents.shape

torch.Size([1, 4, 3])

In [26]:
model.consequents_structure

[         c0 (x0)   c1 (x1)        c2
 rule 1  0.041424  0.568967  0.223800
 rule 2 -0.871883 -0.619813  0.039728
 rule 3 -0.925190  0.031418  0.446851
 rule 4  0.875391 -0.937505 -0.571429]

In [27]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [28]:
model.classes_prediction(x)

tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0]])

In [29]:
model(x)

tensor([[0.3630],
        [0.4273],
        [0.4829],
        [0.3781],
        [0.3794],
        [0.5476],
        [0.4630],
        [0.4017],
        [0.3395],
        [0.4453]], grad_fn=<TBackward0>)

In [30]:
y

tensor([0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [31]:
print(model.fuzzify_layer.premises.grad)
print(model.consequent_layer.consequents.grad)

None
None

In [32]:
model(x)

tensor([[0.3630],
        [0.4273],
        [0.4829],
        [0.3781],
        [0.3794],
        [0.5476],
        [0.4630],
        [0.4017],
        [0.3395],
        [0.4453]], grad_fn=<TBackward0>)

In [33]:
loss = nn.functional.binary_cross_entropy(model(x).squeeze(), y.to(model(x).dtype))
loss

tensor(0.6713, grad_fn=<BinaryCrossEntropyBackward0>)

In [34]:
loss.backward()

In [35]:
print(model.fuzzify_layer.premises.grad)

tensor([[[ 0.0681,  0.1329],
         [-0.0773,  0.1360],
         [ 0.0711, -0.0782],
         [ 0.0441, -0.0701]],

        [[-0.0746, -0.2206],
         [ 0.1214, -0.1020],
         [ 0.0627,  0.2515],
         [ 0.0177, -0.0365]]])

In [36]:
print(model.consequent_layer.consequents.grad)

tensor([[[ 0.0032, -0.0067, -0.0185],
         [ 0.0004, -0.0472, -0.0714],
         [-0.0378, -0.0080, -0.0486],
         [ 0.0508,  0.0462,  0.0613]]])

#### Multiple Outputs

In [40]:
x = torch.rand(10, 3)
y = torch.randint(0, 2, (10, 2))
y

tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 0],
        [0, 1],
        [1, 1],
        [0, 0],
        [0, 0],
        [0, 1]])

In [41]:
model = Type3ANFIS(x, init_rules=4, output_type='binary', outputs_amount=2)
model.premises.shape

torch.Size([3, 4, 2])

In [42]:
model.premises_structure

         mu (x0)  sigma (x0)   mu (x1)  sigma (x1)   mu (x2)  sigma (x2)
rule 1  0.006340    0.149531  0.005656    0.143504  0.054268    0.132029
rule 2  0.305401    0.149531  0.292665    0.143504  0.318327    0.132029
rule 3  0.604463    0.149531  0.579673    0.143504  0.582385    0.132029
rule 4  0.903524    0.149531  0.866682    0.143504  0.846444    0.132029

In [43]:
model.consequents.shape

torch.Size([2, 4, 4])

In [44]:
model.consequents_structure

[         c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1 -0.867228 -0.488104  0.377854  0.392143
 rule 2 -0.065498 -0.911456  0.647900  0.246136
 rule 3  0.506979 -0.566351 -0.017510 -0.467782
 rule 4  0.754290  0.946593  0.093376 -0.164536,
          c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1  0.555679 -0.752614  0.266454  0.419247
 rule 2 -0.810164 -0.601521  0.947116 -0.911706
 rule 3  0.415899 -0.558258  0.347853 -0.384638
 rule 4  0.529314 -0.347217  0.249650 -0.101572]

In [45]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [46]:
model.classes_prediction(x)

tensor([[0, 0],
        [0, 0],
        [1, 0],
        [0, 0],
        [1, 1],
        [1, 0],
        [0, 0],
        [0, 0],
        [1, 0],
        [1, 0]])

In [47]:
model(x)

tensor([[0.3780, 0.2766],
        [0.3150, 0.3905],
        [0.5487, 0.2770],
        [0.3780, 0.1872],
        [0.7791, 0.5524],
        [0.6113, 0.2981],
        [0.3735, 0.3789],
        [0.4231, 0.4539],
        [0.5579, 0.2500],
        [0.5670, 0.2437]], grad_fn=<TBackward0>)

In [48]:
y

tensor([[0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 0],
        [0, 1],
        [1, 1],
        [0, 0],
        [0, 0],
        [0, 1]])

In [50]:
print(model.fuzzify_layer.premises.grad)
print(model.consequent_layer.consequents.grad)

None
None

In [51]:
model(x)

tensor([[0.3780, 0.2766],
        [0.3150, 0.3905],
        [0.5487, 0.2770],
        [0.3780, 0.1872],
        [0.7791, 0.5524],
        [0.6113, 0.2981],
        [0.3735, 0.3789],
        [0.4231, 0.4539],
        [0.5579, 0.2500],
        [0.5670, 0.2437]], grad_fn=<TBackward0>)

In [52]:
loss = nn.functional.binary_cross_entropy(model(x), y.to(model(x).dtype))
loss

tensor(0.8709, grad_fn=<BinaryCrossEntropyBackward0>)

In [53]:
loss.backward()

In [55]:
print(model.fuzzify_layer.premises.grad)

tensor([[[-1.2008e-01, -4.5782e-01],
         [ 1.6214e-02,  1.9659e-01],
         [ 2.8299e-02, -5.1065e-01],
         [ 2.7549e-04, -8.8414e-04]],

        [[ 1.1020e-03, -2.8142e-03],
         [ 5.7603e-02,  7.1999e-01],
         [-1.3220e-01, -3.3085e-01],
         [-4.9540e-03,  2.0529e-03]],

        [[-1.9801e-02, -1.0398e-02],
         [-9.3887e-02, -1.3976e-01],
         [ 8.5838e-02, -8.4462e-02],
         [-5.7421e-02,  7.0915e-02]]])

In [56]:
print(model.consequent_layer.consequents.grad)

tensor([[[ 9.1365e-04, -3.6446e-05,  1.6411e-04,  1.4831e-03],
         [ 4.3156e-02,  2.6394e-02,  2.4709e-02,  8.9111e-02],
         [-4.1265e-03, -2.8934e-02, -1.6354e-02, -3.0457e-02],
         [ 3.2927e-02,  3.0940e-02,  2.3464e-02,  3.6438e-02]],

        [[-1.2569e-03, -3.4379e-07, -2.6696e-04, -2.1435e-03],
         [-3.0689e-02, -5.2287e-02, -2.4314e-02, -1.0940e-01],
         [-4.6203e-03, -1.2090e-02,  1.8834e-02,  1.1258e-03],
         [ 2.3341e-02,  2.1933e-02,  1.6641e-02,  2.5834e-02]]])

### Multiclass classification

In [61]:
x = torch.rand(10, 3)
y = torch.randint(0, 4, (10,))
y

tensor([0, 1, 0, 1, 2, 2, 2, 0, 3, 2])

In [62]:
model = Type3ANFIS(x, init_rules=4, output_type='multiclass', outputs_amount=4)
model.premises.shape

torch.Size([3, 4, 2])

In [63]:
model.premises_structure

         mu (x0)  sigma (x0)   mu (x1)  sigma (x1)   mu (x2)  sigma (x2)
rule 1  0.112382    0.138908  0.005835    0.154319  0.028630    0.120011
rule 2  0.390199    0.138908  0.314474    0.154319  0.268653    0.120011
rule 3  0.668015    0.138908  0.623112    0.154319  0.508676    0.120011
rule 4  0.945832    0.138908  0.931750    0.154319  0.748699    0.120011

In [64]:
model.consequents.shape

torch.Size([4, 4, 4])

In [65]:
model.consequents_structure

[         c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1 -0.769474 -0.004419  0.608707  0.292761
 rule 2 -0.588900  0.316534 -0.987255 -0.970743
 rule 3 -0.402161  0.350674 -0.224576 -0.807115
 rule 4 -0.305235 -0.547563 -0.454264 -0.031327,
          c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1  0.477317 -0.205667 -0.223859  0.270563
 rule 2 -0.003505  0.965952  0.964386 -0.725056
 rule 3  0.668248  0.230898 -0.211038  0.597987
 rule 4  0.926570  0.060539 -0.289810 -0.965078,
          c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1  0.795851  0.464839  0.147551  0.932903
 rule 2 -0.592016 -0.365358 -0.867434  0.460477
 rule 3 -0.782143  0.806213  0.567436  0.725355
 rule 4  0.615417 -0.104871 -0.962379  0.023021,
          c0 (x0)   c1 (x1)   c2 (x2)        c3
 rule 1 -0.818597 -0.831664 -0.443350  0.703026
 rule 2 -0.307847 -0.722103 -0.658649 -0.696005
 rule 3  0.561743 -0.686109 -0.263647  0.447188
 rule 4  0.303259  0.403277 -0.207169  0.782958]

In [66]:
loader = data.DataLoader(data.TensorDataset(x, y), batch_size = 2)
x = loader.dataset.tensors[0]
y = loader.dataset.tensors[1]

In [67]:
model.classes_prediction(x)

tensor([2, 2, 1, 2, 1, 2, 1, 1, 1, 2])

In [68]:
model(x)

tensor([[0.1316, 0.3603, 0.3916, 0.1164],
        [0.1882, 0.1849, 0.4040, 0.2229],
        [0.0794, 0.4323, 0.3489, 0.1394],
        [0.0561, 0.3803, 0.4332, 0.1304],
        [0.0467, 0.4208, 0.2891, 0.2435],
        [0.0532, 0.2933, 0.5333, 0.1202],
        [0.0529, 0.5054, 0.2274, 0.2142],
        [0.1035, 0.3857, 0.3832, 0.1275],
        [0.0530, 0.4101, 0.3530, 0.1838],
        [0.1221, 0.2502, 0.4684, 0.1593]], grad_fn=<TBackward0>)

In [69]:
y

tensor([0, 1, 0, 1, 2, 2, 2, 0, 3, 2])

In [70]:
print(model.fuzzify_layer.premises.grad)
print(model.consequent_layer.consequents.grad)

None
None

In [71]:
model(x)

tensor([[0.1316, 0.3603, 0.3916, 0.1164],
        [0.1882, 0.1849, 0.4040, 0.2229],
        [0.0794, 0.4323, 0.3489, 0.1394],
        [0.0561, 0.3803, 0.4332, 0.1304],
        [0.0467, 0.4208, 0.2891, 0.2435],
        [0.0532, 0.2933, 0.5333, 0.1202],
        [0.0529, 0.5054, 0.2274, 0.2142],
        [0.1035, 0.3857, 0.3832, 0.1275],
        [0.0530, 0.4101, 0.3530, 0.1838],
        [0.1221, 0.2502, 0.4684, 0.1593]], grad_fn=<TBackward0>)

In [72]:
loss = nn.functional.cross_entropy(model(x), y)
loss.backward()

In [73]:
print(model.fuzzify_layer.premises.grad)

tensor([[[-0.0139, -0.0428],
         [-0.0168, -0.1105],
         [ 0.0321,  0.0321],
         [ 0.0098,  0.0158]],

        [[-0.0048, -0.0055],
         [-0.0098, -0.0296],
         [ 0.0127,  0.0210],
         [ 0.0120, -0.0099]],

        [[ 0.0035,  0.0029],
         [ 0.0041, -0.0024],
         [-0.0375,  0.0976],
         [ 0.0428, -0.0944]]])

In [74]:
print(model.consequent_layer.consequents.grad)

tensor([[[ 5.3567e-04,  5.0451e-05,  6.3301e-04,  3.1428e-03],
         [-6.9066e-03, -8.1954e-03, -9.6631e-03, -2.4403e-02],
         [ 3.7406e-03,  4.5591e-03,  3.2580e-03,  6.2047e-03],
         [ 5.1948e-05,  6.4942e-05,  4.4291e-05,  8.1255e-05]],

        [[-1.0539e-03,  9.6650e-05, -3.3385e-03, -1.3368e-02],
         [ 1.1337e-02,  6.3797e-03,  5.2914e-03,  2.4510e-02],
         [ 1.9909e-02,  6.9539e-03,  1.3791e-02,  2.4875e-02],
         [ 4.5080e-04,  4.5151e-04,  3.4178e-04,  6.0701e-04]],

        [[-2.1217e-04, -2.6926e-04,  1.8661e-03,  6.1132e-03],
         [-8.9093e-03, -1.1070e-04,  3.4289e-03, -9.0354e-03],
         [-2.5127e-02, -1.2101e-02, -1.9853e-02, -3.6361e-02],
         [ 3.6270e-04,  3.2921e-04,  1.0988e-04,  3.7428e-04]],

        [[ 7.3040e-04,  1.2216e-04,  8.3947e-04,  4.1121e-03],
         [ 4.4793e-03,  1.9263e-03,  9.4279e-04,  8.9288e-03],
         [ 1.4776e-03,  5.8773e-04,  2.8042e-03,  5.2814e-03],
         [-8.6545e-04, -8.4566e-04, -4.9596e-04, -1.0625e-03]]])