## Imports

In [2]:
import sys
import os
import torch
import torch.utils.data as data
import torch.nn as nn

sys.path.append(os.path.abspath('../../'))

import neuro_fuzzy_toolbox as nft

In [3]:
import numpy as np

In [4]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Multiclass Classification

## Data

In [5]:
from ucimlrepo import fetch_ucirepo

In [6]:
heart_disease = fetch_ucirepo(id=45)

X = heart_disease.data.features
y = heart_disease.data.targets

In [7]:
X = X.fillna(value=0)

In [8]:
y

     num
0      0
1      2
2      1
3      0
4      0
..   ...
298    1
299    2
300    3
301    1
302    0

[303 rows x 1 columns]

In [9]:
y = y.copy()
y.loc[y["num"] > 0, "num"] = 1

In [10]:
y

     num
0      0
1      1
2      1
3      0
4      0
..   ...
298    1
299    1
300    1
301    1
302    0

[303 rows x 1 columns]

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.5, stratify=y)

In [12]:
unique_classes, counts = np.unique(y_train.values, return_counts=True)
print(unique_classes)
print(counts)

[0 1]
[82 69]

In [13]:
unique_classes, counts = np.unique(y_test.values, return_counts=True)
print(unique_classes)
print(counts)

[0 1]
[82 70]

In [14]:
scaler = MinMaxScaler(feature_range=(-1, 1))

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

In [15]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train.values).squeeze()
y_test = torch.from_numpy(y_test.values).squeeze()

In [16]:
y_train.dtype

torch.int64

In [17]:
x_train = x_train.type(torch.float64)
x_test = x_test.type(torch.float64)

In [18]:
loader = data.DataLoader(data.TensorDataset(x_train, y_train), batch_size = 4, shuffle = True)
x_trainset = loader.dataset.tensors[0]
y_trainset = loader.dataset.tensors[1]

In [19]:
y_trainset.dtype

torch.int64

## Model & Training

In [20]:
2**13

8192

In [21]:
model = nft.h_ANFIS(
    input_size = 13,
    num_mfs = 40,
    outputs = 2,
    #membership_function=nft.Gaussian_MF,
    rule_reduced = True,
    output_type='multiclass',
    dtype=torch.float64
)

#model.init_premises(x_trainset)

#model.init_consequents(x_trainset, y_trainset)

In [22]:
loss_fn = nn.functional.cross_entropy

optimizer = torch.optim.AdamW
params = {'lr': 0.0001, 'weight_decay': 0.001}
#optimizer = torch.optim.Adam
#params = {'lr': 0.005}
#optimizer = torch.optim.SGD
#params = {'lr': 0.001, 'momentum': 0.9}

early_stopping = nft.EarlyStopping(
    patience=50, 
    delta=0.01
)

In [23]:
trainer = nft.Basic_optimizer_training_algorithm(
    epochs=1000,
    loss_function=loss_fn,
    optimizer=optimizer,
    optimizer_params=params,
    validation=0.3,
    early_stopping=early_stopping
)

In [24]:
trainer(model, loader, verbose=True)

Epoch:    1/1000 - loss: 0.974338 - validation loss: 1.063101
Epoch:    2/1000 - loss: 0.957909 - validation loss: 1.058151
Epoch:    3/1000 - loss: 0.938391 - validation loss: 1.052303
Epoch:    4/1000 - loss: 0.921922 - validation loss: 1.049007
Epoch:    5/1000 - loss: 0.903449 - validation loss: 1.043822
Epoch:    6/1000 - loss: 0.884889 - validation loss: 1.038224
Epoch:    7/1000 - loss: 0.865231 - validation loss: 1.032736
Epoch:    8/1000 - loss: 0.849510 - validation loss: 1.027797
Epoch:    9/1000 - loss: 0.828961 - validation loss: 1.021885
Epoch:   10/1000 - loss: 0.812075 - validation loss: 1.017436
Epoch:   11/1000 - loss: 0.796713 - validation loss: 1.012304
Epoch:   12/1000 - loss: 0.779604 - validation loss: 1.005931
Epoch:   13/1000 - loss: 0.761540 - validation loss: 1.000204
Epoch:   14/1000 - loss: 0.746851 - validation loss: 0.997523
Epoch:   15/1000 - loss: 0.731778 - validation loss: 0.991411
Epoch:   16/1000 - loss: 0.714950 - validation loss: 0.985657
Epoch:   17/1000 - loss: 0.699728 - validation loss: 0.980248
Epoch:   18/1000 - loss: 0.684776 - validation loss: 0.973397
Epoch:   19/1000 - loss: 0.670563 - validation loss: 0.968618
Epoch:   20/1000 - loss: 0.660303 - validation loss: 0.967122
Epoch:   21/1000 - loss: 0.647959 - validation loss: 0.961355
Epoch:   22/1000 - loss: 0.636558 - validation loss: 0.956022
Epoch:   23/1000 - loss: 0.627023 - validation loss: 0.953158
Epoch:   24/1000 - loss: 0.617233 - validation loss: 0.948245
Epoch:   25/1000 - loss: 0.609091 - validation loss: 0.946312
Epoch:   26/1000 - loss: 0.600966 - validation loss: 0.941526
Epoch:   27/1000 - loss: 0.593198 - validation loss: 0.938822
Epoch:   28/1000 - loss: 0.585944 - validation loss: 0.937772
Epoch:   29/1000 - loss: 0.579580 - validation loss: 0.934616
Epoch:   30/1000 - loss: 0.573166 - validation loss: 0.931993
Epoch:   31/1000 - loss: 0.565950 - validation loss: 0.930616
Epoch:   32/1000 - loss: 0.559954 - validation loss: 0.929255
Epoch:   33/1000 - loss: 0.554163 - validation loss: 0.927539
Epoch:   34/1000 - loss: 0.548094 - validation loss: 0.925997
Epoch:   35/1000 - loss: 0.542669 - validation loss: 0.922832
Epoch:   36/1000 - loss: 0.536511 - validation loss: 0.919790
Epoch:   37/1000 - loss: 0.531156 - validation loss: 0.919635
Epoch:   38/1000 - loss: 0.525202 - validation loss: 0.917830
Epoch:   39/1000 - loss: 0.517614 - validation loss: 0.918996
Epoch:   40/1000 - loss: 0.512151 - validation loss: 0.915797
Epoch:   41/1000 - loss: 0.504764 - validation loss: 0.913415
Epoch:   42/1000 - loss: 0.499411 - validation loss: 0.910306
Epoch:   43/1000 - loss: 0.494211 - validation loss: 0.907187
Epoch:   44/1000 - loss: 0.489308 - validation loss: 0.905017
Epoch:   45/1000 - loss: 0.484518 - validation loss: 0.901250
Epoch:   46/1000 - loss: 0.479024 - validation loss: 0.895393
Epoch:   47/1000 - loss: 0.473741 - validation loss: 0.885540
Epoch:   48/1000 - loss: 0.468655 - validation loss: 0.879484
Epoch:   49/1000 - loss: 0.462575 - validation loss: 0.867351
Epoch:   50/1000 - loss: 0.457445 - validation loss: 0.862265
Epoch:   51/1000 - loss: 0.451120 - validation loss: 0.852413
Epoch:   52/1000 - loss: 0.446255 - validation loss: 0.846570
Epoch:   53/1000 - loss: 0.441061 - validation loss: 0.839772
Epoch:   54/1000 - loss: 0.436212 - validation loss: 0.836803
Epoch:   55/1000 - loss: 0.430774 - validation loss: 0.829063
Epoch:   56/1000 - loss: 0.426079 - validation loss: 0.827344
Epoch:   57/1000 - loss: 0.421491 - validation loss: 0.819332
Epoch:   58/1000 - loss: 0.416802 - validation loss: 0.816352
Epoch:   59/1000 - loss: 0.412429 - validation loss: 0.813518
Epoch:   60/1000 - loss: 0.407904 - validation loss: 0.809158
Epoch:   61/1000 - loss: 0.403883 - validation loss: 0.805462
Epoch:   62/1000 - loss: 0.400040 - validation loss: 0.799204
Epoch:   63/1000 - loss: 0.396002 - validation loss: 0.797605
Epoch:   64/1000 - loss: 0.392415 - validation loss: 0.795994
Epoch:   65/1000 - loss: 0.389162 - validation loss: 0.791898
Epoch:   66/1000 - loss: 0.385885 - validation loss: 0.788836
Epoch:   67/1000 - loss: 0.383052 - validation loss: 0.787514
Epoch:   68/1000 - loss: 0.379855 - validation loss: 0.786051
Epoch:   69/1000 - loss: 0.377014 - validation loss: 0.784950
Epoch:   70/1000 - loss: 0.374461 - validation loss: 0.782591
Epoch:   71/1000 - loss: 0.371629 - validation loss: 0.780511
Epoch:   72/1000 - loss: 0.369351 - validation loss: 0.780374
Epoch:   73/1000 - loss: 0.366830 - validation loss: 0.779203
Epoch:   74/1000 - loss: 0.364544 - validation loss: 0.776876
Epoch:   75/1000 - loss: 0.362304 - validation loss: 0.774908
Epoch:   76/1000 - loss: 0.359635 - validation loss: 0.773983
Epoch:   77/1000 - loss: 0.357195 - validation loss: 0.769680
Epoch:   78/1000 - loss: 0.354414 - validation loss: 0.766936
Epoch:   79/1000 - loss: 0.351723 - validation loss: 0.760481
Epoch:   80/1000 - loss: 0.349261 - validation loss: 0.757601
Epoch:   81/1000 - loss: 0.347108 - validation loss: 0.755143
Epoch:   82/1000 - loss: 0.344680 - validation loss: 0.749548
Epoch:   83/1000 - loss: 0.342779 - validation loss: 0.744605
Epoch:   84/1000 - loss: 0.341042 - validation loss: 0.741540
Epoch:   85/1000 - loss: 0.339115 - validation loss: 0.741890
Epoch:   86/1000 - loss: 0.337667 - validation loss: 0.738702
Epoch:   87/1000 - loss: 0.335930 - validation loss: 0.735975
Epoch:   88/1000 - loss: 0.334233 - validation loss: 0.736814
Epoch:   89/1000 - loss: 0.332505 - validation loss: 0.734832
Epoch:   90/1000 - loss: 0.330981 - validation loss: 0.733969
Epoch:   91/1000 - loss: 0.329433 - validation loss: 0.733806
Epoch:   92/1000 - loss: 0.327730 - validation loss: 0.730267
Epoch:   93/1000 - loss: 0.326190 - validation loss: 0.729744
Epoch:   94/1000 - loss: 0.324808 - validation loss: 0.730975
Epoch:   95/1000 - loss: 0.323356 - validation loss: 0.730109
Epoch:   96/1000 - loss: 0.321792 - validation loss: 0.729514
Epoch:   97/1000 - loss: 0.320268 - validation loss: 0.728761
Epoch:   98/1000 - loss: 0.318886 - validation loss: 0.725547
Epoch:   99/1000 - loss: 0.317402 - validation loss: 0.724736
Epoch:  100/1000 - loss: 0.316086 - validation loss: 0.725199
Epoch:  101/1000 - loss: 0.314794 - validation loss: 0.724166
Epoch:  102/1000 - loss: 0.313379 - validation loss: 0.723164
Epoch:  103/1000 - loss: 0.311791 - validation loss: 0.723016
Epoch:  104/1000 - loss: 0.310434 - validation loss: 0.721801
Epoch:  105/1000 - loss: 0.308985 - validation loss: 0.721497
Epoch:  106/1000 - loss: 0.307327 - validation loss: 0.717736
Epoch:  107/1000 - loss: 0.306011 - validation loss: 0.716554
Epoch:  108/1000 - loss: 0.304703 - validation loss: 0.718253
Epoch:  109/1000 - loss: 0.303241 - validation loss: 0.717133
Epoch:  110/1000 - loss: 0.302077 - validation loss: 0.717038
Epoch:  111/1000 - loss: 0.300589 - validation loss: 0.714777
Epoch:  112/1000 - loss: 0.299306 - validation loss: 0.716279
Epoch:  113/1000 - loss: 0.298041 - validation loss: 0.716424
Epoch:  114/1000 - loss: 0.296807 - validation loss: 0.715839
Epoch:  115/1000 - loss: 0.295609 - validation loss: 0.716252
Epoch:  116/1000 - loss: 0.294480 - validation loss: 0.715457
Epoch:  117/1000 - loss: 0.293301 - validation loss: 0.715756
Epoch:  118/1000 - loss: 0.291961 - validation loss: 0.716277
Epoch:  119/1000 - loss: 0.290851 - validation loss: 0.718473
Epoch:  120/1000 - loss: 0.289666 - validation loss: 0.718454
Epoch:  121/1000 - loss: 0.288543 - validation loss: 0.717840
Epoch:  122/1000 - loss: 0.287430 - validation loss: 0.718264
Epoch:  123/1000 - loss: 0.286298 - validation loss: 0.715780
Epoch:  124/1000 - loss: 0.284997 - validation loss: 0.715154
Epoch:  125/1000 - loss: 0.283950 - validation loss: 0.715738
Epoch:  126/1000 - loss: 0.282853 - validation loss: 0.714471
Epoch:  127/1000 - loss: 0.281736 - validation loss: 0.713468
Epoch:  128/1000 - loss: 0.280747 - validation loss: 0.712866
Epoch:  129/1000 - loss: 0.279672 - validation loss: 0.712245
Epoch:  130/1000 - loss: 0.278650 - validation loss: 0.712647
Epoch:  131/1000 - loss: 0.277591 - validation loss: 0.711433
Epoch:  132/1000 - loss: 0.276570 - validation loss: 0.711953
Epoch:  133/1000 - loss: 0.275570 - validation loss: 0.711377
Epoch:  134/1000 - loss: 0.274455 - validation loss: 0.711174
Epoch:  135/1000 - loss: 0.273522 - validation loss: 0.712013
Epoch:  136/1000 - loss: 0.272485 - validation loss: 0.710771
Epoch:  137/1000 - loss: 0.271510 - validation loss: 0.711065
Epoch:  138/1000 - loss: 0.270498 - validation loss: 0.709547
Epoch:  139/1000 - loss: 0.269448 - validation loss: 0.709668
Epoch:  140/1000 - loss: 0.268444 - validation loss: 0.710258
Epoch:  141/1000 - loss: 0.267434 - validation loss: 0.709069
Epoch:  142/1000 - loss: 0.266493 - validation loss: 0.710593
Epoch:  143/1000 - loss: 0.265507 - validation loss: 0.710842
Epoch:  144/1000 - loss: 0.264578 - validation loss: 0.709301
Epoch:  145/1000 - loss: 0.263598 - validation loss: 0.708598
Epoch:  146/1000 - loss: 0.262528 - validation loss: 0.709379
Epoch:  147/1000 - loss: 0.261605 - validation loss: 0.708930
Epoch:  148/1000 - loss: 0.260658 - validation loss: 0.707945
Epoch:  149/1000 - loss: 0.259557 - validation loss: 0.708555
Epoch:  150/1000 - loss: 0.258640 - validation loss: 0.707417
Epoch:  151/1000 - loss: 0.257471 - validation loss: 0.707667
Epoch:  152/1000 - loss: 0.256458 - validation loss: 0.707717
Epoch:  153/1000 - loss: 0.255494 - validation loss: 0.704693
Epoch:  154/1000 - loss: 0.254441 - validation loss: 0.706817
Epoch:  155/1000 - loss: 0.253394 - validation loss: 0.706107
Epoch:  156/1000 - loss: 0.252389 - validation loss: 0.706920
Epoch:  157/1000 - loss: 0.251380 - validation loss: 0.704502
Epoch:  158/1000 - loss: 0.250351 - validation loss: 0.708594
Epoch:  159/1000 - loss: 0.249325 - validation loss: 0.707798
Epoch:  160/1000 - loss: 0.248342 - validation loss: 0.707483
Epoch:  161/1000 - loss: 0.247140 - validation loss: 0.706277
Epoch:  162/1000 - loss: 0.246119 - validation loss: 0.705227
Epoch:  163/1000 - loss: 0.245029 - validation loss: 0.705149
Epoch:  164/1000 - loss: 0.244113 - validation loss: 0.704978
Epoch:  165/1000 - loss: 0.242992 - validation loss: 0.704743
Epoch:  166/1000 - loss: 0.241990 - validation loss: 0.704948
Epoch:  167/1000 - loss: 0.240974 - validation loss: 0.705161
Epoch:  168/1000 - loss: 0.240083 - validation loss: 0.700353
Epoch:  169/1000 - loss: 0.238918 - validation loss: 0.700452
Epoch:  170/1000 - loss: 0.237819 - validation loss: 0.701836
Epoch:  171/1000 - loss: 0.236651 - validation loss: 0.702794
Epoch:  172/1000 - loss: 0.235493 - validation loss: 0.702285
Epoch:  173/1000 - loss: 0.234423 - validation loss: 0.702839
Epoch:  174/1000 - loss: 0.233282 - validation loss: 0.703073
Epoch:  175/1000 - loss: 0.232067 - validation loss: 0.704653
Epoch:  176/1000 - loss: 0.230990 - validation loss: 0.705672
Epoch:  177/1000 - loss: 0.229956 - validation loss: 0.703883
Epoch:  178/1000 - loss: 0.228972 - validation loss: 0.706258
Epoch:  179/1000 - loss: 0.227879 - validation loss: 0.705646
Epoch:  180/1000 - loss: 0.226890 - validation loss: 0.705637
Epoch:  181/1000 - loss: 0.225849 - validation loss: 0.706527
Epoch:  182/1000 - loss: 0.224885 - validation loss: 0.707239
Epoch:  183/1000 - loss: 0.223819 - validation loss: 0.706806
Epoch:  184/1000 - loss: 0.222865 - validation loss: 0.706762
Epoch:  185/1000 - loss: 0.221733 - validation loss: 0.708098
Epoch:  186/1000 - loss: 0.220760 - validation loss: 0.707536
Epoch:  187/1000 - loss: 0.219835 - validation loss: 0.710106
Epoch:  188/1000 - loss: 0.218825 - validation loss: 0.710676
Epoch:  189/1000 - loss: 0.217879 - validation loss: 0.710876
Epoch:  190/1000 - loss: 0.216864 - validation loss: 0.711458
Epoch:  191/1000 - loss: 0.215954 - validation loss: 0.711344
Epoch:  192/1000 - loss: 0.214923 - validation loss: 0.712785
Epoch:  193/1000 - loss: 0.213925 - validation loss: 0.713677
Epoch:  194/1000 - loss: 0.213097 - validation loss: 0.712456
Epoch:  195/1000 - loss: 0.212125 - validation loss: 0.713179
Epoch:  196/1000 - loss: 0.211095 - validation loss: 0.714533
Epoch:  197/1000 - loss: 0.210090 - validation loss: 0.714835
Epoch:  198/1000 - loss: 0.209072 - validation loss: 0.715274
Epoch:  199/1000 - loss: 0.208216 - validation loss: 0.714969
Epoch:  200/1000 - loss: 0.207304 - validation loss: 0.715700
Epoch:  201/1000 - loss: 0.206280 - validation loss: 0.715793
Epoch:  202/1000 - loss: 0.205316 - validation loss: 0.716302
Epoch:  203/1000 - loss: 0.204444 - validation loss: 0.714907
Epoch:  204/1000 - loss: 0.203409 - validation loss: 0.716371
Epoch:  205/1000 - loss: 0.202482 - validation loss: 0.718022
Epoch:  206/1000 - loss: 0.201523 - validation loss: 0.717093
Epoch:  207/1000 - loss: 0.200654 - validation loss: 0.716846
Epoch:  208/1000 - loss: 0.199716 - validation loss: 0.717614
Epoch:  209/1000 - loss: 0.198817 - validation loss: 0.719079
Epoch:  210/1000 - loss: 0.197767 - validation loss: 0.719960
Epoch:  211/1000 - loss: 0.196803 - validation loss: 0.720180
Epoch:  212/1000 - loss: 0.195827 - validation loss: 0.719582
Epoch:  213/1000 - loss: 0.194750 - validation loss: 0.720605
Epoch:  214/1000 - loss: 0.193885 - validation loss: 0.721551
Epoch:  215/1000 - loss: 0.193043 - validation loss: 0.722498
Epoch:  216/1000 - loss: 0.192166 - validation loss: 0.720500
Epoch:  217/1000 - loss: 0.191247 - validation loss: 0.724005
Early stopping
Training finished

In [25]:
train_measures = nft.get_measures(model, x_trainset, y_trainset)
for measure in train_measures:
    print(measure + ':', train_measures[measure])

Accuracy: 0.8807947019867549
Precision: 0.8813301899086591
Recall: 0.8807947019867549
F1: 0.8804346291249523
Confusion Matrix: [[75  7]
 [11 58]]

In [26]:
test_measures = nft.get_measures(model, x_test, y_test)
for measure in test_measures:
    print(measure + ':', test_measures[measure])

Accuracy: 0.7631578947368421
Precision: 0.7633261064593302
Recall: 0.7631578947368421
F1: 0.7620350261078509
Confusion Matrix: [[67 15]
 [21 49]]